"""RoboChallenge Table30v2 — data_config / embodiments / mixtures.

Auto-discovered by ``starVLA.dataloader.gr00t_lerobot.registry.discover_and_merge``.

Datasets live at::

    playground/Datasets/RoboChallenge_table30v2/lerobot/<task>/

each generated by ``examples/realRobots/RoboChallenge_table30v2/train_files/convert_robochallenge_to_lerobot.py``.

Schema (single-arm: UR5 / ARX5 / DOS-W1 — see converter):
* observation.state (7,) = joint_positions(6) + gripper_width(1)
* action            (8,) = ee_positions(7 quat: tx,ty,tz,rx,ry,rz,rw) + gripper_width(1)
* video keys vary by embodiment (see ``CAMERAS`` in the converter).
"""
from starVLA.dataloader.gr00t_lerobot.datasets import ModalityConfig
from starVLA.dataloader.gr00t_lerobot.transform.base import ComposedModalityTransform
from starVLA.dataloader.gr00t_lerobot.transform.state_action import (
    StateActionToTensor,
    StateActionTransform,
)
from starVLA.dataloader.gr00t_lerobot.embodiment_tags import EmbodimentTag


class _RoboChallengeUR5Config:
    """RoboChallenge Table30v2 — UR5 single-arm (2 cameras: cam_global, cam_arm)."""
    video_keys = ["video.cam_global", "video.cam_arm"]
    state_keys = ["state.joint_positions", "state.gripper_width"]
    action_keys = ["action.ee_positions", "action.gripper_width"]
    language_keys = ["annotation.human.task_description"]

    observation_indices = [0]
    action_indices = list(range(8))

    def modality_config(self):
        return {
            "video":     ModalityConfig(delta_indices=self.observation_indices, modality_keys=self.video_keys),
            "state":     ModalityConfig(delta_indices=self.observation_indices, modality_keys=self.state_keys),
            "action":    ModalityConfig(delta_indices=self.action_indices,      modality_keys=self.action_keys),
            "language":  ModalityConfig(delta_indices=self.observation_indices, modality_keys=self.language_keys),
        }

    def transform(self):
        return ComposedModalityTransform(transforms=[
            StateActionToTensor(apply_to=self.state_keys),
            StateActionTransform(
                apply_to=self.state_keys,
                normalization_modes={k: "min_max" for k in self.state_keys},
            ),
            StateActionToTensor(apply_to=self.action_keys),
            StateActionTransform(
                apply_to=self.action_keys,
                normalization_modes={k: "min_max" for k in self.action_keys},
            ),
        ])


class _RoboChallengeARX5Config(_RoboChallengeUR5Config):
    """ARX5 single-arm (3 cameras: cam_global, cam_arm, cam_side)."""
    video_keys = ["video.cam_global", "video.cam_arm", "video.cam_side"]


class _RoboChallengeDOSW1Config(_RoboChallengeUR5Config):
    """DOS-W1 single-arm (3 cameras: cam_high, cam_left_wrist, cam_right_wrist)."""
    video_keys = ["video.cam_high", "video.cam_left_wrist", "video.cam_right_wrist"]


ROBOT_TYPE_CONFIG_MAP = {
    "ur5_robochallenge":   _RoboChallengeUR5Config(),
    "arx5_robochallenge":  _RoboChallengeARX5Config(),
    "dosw1_robochallenge": _RoboChallengeDOSW1Config(),
}

ROBOT_TYPE_TO_EMBODIMENT_TAG = {
    "ur5_robochallenge":   EmbodimentTag.NEW_EMBODIMENT,
    "arx5_robochallenge":  EmbodimentTag.NEW_EMBODIMENT,
    "dosw1_robochallenge": EmbodimentTag.NEW_EMBODIMENT,
}


# Single-arm tasks shipped by Table30v2 (verified per-task via task_info.json).
# Mapping is task_name -> embodiment tag. Update as more tasks finish converting.
_UR5_TASKS = {
    "arrange_fruits",
    "shred_paper",
}
_ARX5_TASKS: set[str] = {
    "arrange_flowers",
}      # filled after conversion
_DOSW1_TASKS: set[str] = {
    "fold_the_clothes",
}


def _entries(task_set, robot_tag):
    return [(f"lerobot/{t}", 1.0, robot_tag) for t in sorted(task_set)]


DATASET_NAMED_MIXTURES = {
    # --- minimal walk-through (1 task) ---
    "robochallenge_table30v2_shred_paper": [
        ("lerobot/shred_paper", 1.0, "ur5_robochallenge"),
    ],
    # --- per-embodiment ---
    "robochallenge_table30v2_ur5_all":   _entries(_UR5_TASKS,   "ur5_robochallenge"),
    "robochallenge_table30v2_arx5_all":  _entries(_ARX5_TASKS,  "arx5_robochallenge"),
    "robochallenge_table30v2_dosw1_all": _entries(_DOSW1_TASKS, "dosw1_robochallenge"),
}
